package com.cradlerest.web.util.datagen.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Defines the amount of instances to generate for this class relative to the
 * amount generated for another class.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface DataGenRelativeAmount {

	/**
	 * The base class to reference when determining the amount of instances to
	 * generate.
	 */
	Class<?> base();

	/**
	 * The number of instances generated will be equal to the number of instances
	 * generated by the base class times this multiplier.
	 *
	 * May not be < 0.
	 */
	double multiplier();
}
