stages:
  - build
  - test

build:
  stage: build
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn compile

unit-test:
  stage: test
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn test

integration-test:
  stage: test
  image: docker
  services:
    - docker:dind    
  before_script:
    - cd cradletest
  script:
    - docker network create -d bridge ci-network 
    - docker build -f ci-scripts/Dockerfile-db . -t 'cradlerest/db:latest'
    - docker run --privileged --name db --network ci-network -d 'cradlerest/db:latest'
    - docker build -f ci-scripts/Dockerfile-web . -t 'cradlerest/web:latest'
    - docker run --name web --network ci-network -d 'cradlerest/web:latest'
    - docker build -f cradletest/Dockerfile . -t 'cradlerest/tester:latest'
    - docker run --name tester --network ci-network 'cradlerest/tester:latest'

