stages:
  - build
  - unit-test
  - integration-test

build:
  stage: build
  image: "maven:latest"
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn compile

unit-test:
  stage: unit-test
  image: "maven:latest"
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn test

integration-test:
  stage: integration-test
  image: docker
  services:
    - docker:dind    
  before_script:
    - cd cradletest
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up --build --force-recreate --abort-on-container-exit --exit-code-from tester
