stages:
  - build
  - test

build:
  stage: build
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn compile

unit-test:
  stage: test
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn test

integration-test:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - pwd
    - ls
    - docker run --name db -p '3306:3306' --mount "type=bind,src=$CI_PROJECT_DIR/web/scripts/db-initializer-scripts,dst=/docker-entrypoint-initdb.d" -d 'mysql/mysql-server'
    - cd ci-scripts
    - docker build -t cradlerest:latest .
    - docker run --name web -p '9000:9000' -d 'cradlerest:latest'
    - cd ..
    - docker build -f cradletest/Dockerfile . -t 'tester:latest'
    - docker run --name tester 'tester:latest'
