stages:
  - build
  - test

build:
  stage: build
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn compile

unit-test:
  stage: test
  image: maven:latest
  cache:
    paths:
      - .m2/repository/
      - web/target/
  before_script:
    - cd web
  script:
    - mvn test

integration-test:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - docker build -f ci-scripts/Dockerfile-db . -t 'cradlerest/db:latest'
    - docker run --privileged --name db -p '3306:3306' -d 'cradlerest/db:latest'
    - cd ci-scripts
    - docker build -f Dockerfile-web . -t 'cradlerest/web:latest'
    - docker run --name web -p '9000:9000' -d 'cradlerest/web:latest'
    - cd ..
    - docker build -f cradletest/Dockerfile . -t 'cradlerest/tester:latest'
    - docker run --name tester 'tester:latest'
